DefaultContentLanguage: "en"
menu:                   "main"
taxonomies:
  tag:                  "tags"
  pinned:               "pinned"
baseURL:                "/"
languages:
  en:
    weight :            0
    languageName :      "English"
    baseURL:            "/"
    title:              "jarboleda.me"
    email:              "me@jarboleda.me"
    menu:
      main:
      - Name:           "home"
        URL:            "/"
        weight:         1
      - Name:           "about me"
        URL:            "/resume/"
        weight:         2
      - Name:           "projects"
        URL:            "/projects-info/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    disqusShortname :   "jarboleda-me"
    params:             locale = "en-US"
  es:
    weight :            1
    languageName :      "Spanish"
    baseURL:            "/"
    title:              "jarboleda.me"
    email:              "me@jarboleda.me"
    menu:
      main:
      - Name:           "home"
        URL:            "/"
        weight:         1
      - Name:           "sobre mi"
        URL:            "/resume/"
        weight:         2
      - Name:           "proyectos"
        URL:            "/projects-info/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    taxonomies:
        tag:            "tags"
        pinned:         "pinned"
    params:             locale = "es-ES"
# pygmentsuseclasses:   true # see https://github.com/richleland/pygments-css
