DefaultContentLanguage: "en"
menu:                   "main"
taxonomies:
  tag:                  "tags"
  pinned:               "pinned"
  serie:                "series"
  project:              "project"
paginate:               5
baseURL:                "https://www.jarboleda.me"
MetaDataFormat:         "YAML"
languages:
  en:
    weight :            0
    languageName :      "English"
    baseURL:            "https://www.jarboleda.me"
    title:              "Arboleda"
    email:              "me@jarboleda.me"
    locale:             "en-US"
    description:        "The blog of Jeferson Arboleda, software engineer. It's focused on self improvement and overcoming challenges I find everyday"
    formspree:          "https://formspree.io/me@jarboleda.me"
    article_images :    "/content/articles/img/"
    menu:
      main:
      - Name:           "home"
        URL:            "/"
        weight:         1
      - Name:           "about me"
        URL:            "/extras/cv/"
        weight:         2
      - Name:           "projects"
        URL:            "/projects/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    disqusShortname :   "jarboleda-me"
    social:             #web social
      github:           jag10
      gitlab:           jag7
      # facebook:         nozzleio
      # facebook_admin:   '17807199'
      twitter:          j_a_g_x
      # twitter_domain:   nozzle.io
      # googleplus:       NozzleIo
      # pinterest:        nozzleio
      # instagram:        nozzleio
      # youtube:          nozzleio
      linkedin:         "jeferson-arboleda-167429134"
    authors:
      Jeferson:
        name:           Jeferson Arboleda
        thumbnail:      'me2.min.png'
        images:
          - 'me2.png'
        bio:            'Looking for a challenge :) | Currently interested in [Docker](https://docker.com), [kubernetes](https://kubernetes.io/),
                          and [IBM bluemix](https://www.ibm.com/cloud-computing/bluemix/)'
        email:          me@jarboleda.me
        social:
          github:       jag10
          gitlab:       jag7
          # facebook:     killskynet
          twitter:      j_a_g_x
          # googleplus:   killskynet
          # pinterest:    killskynet
          # instagram:    killskynet
          # youtube:      killskynet
          linkedin:     167429134
      # Sarah:            {}
  es:
    weight :            1
    languageName :      "Spanish"
    baseURL:            "https://www.jarboleda.me"
    title:              "Arboleda"
    email:              "me@jarboleda.me"
    locale:             "es-ES"
    description:        "site description goes here"
    formspree:          "https://formspree.io/me@jarboleda.me"
    article_images :    "/content/articles/img/"
    menu:
      main:
      - Name:           "home"
        URL:            "/es"
        weight:         1
      - Name:           "sobre mi"
        URL:            "/extras/cv/"
        weight:         2
      - Name:           "proyectos"
        URL:            "/projects/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    disqusShortname :   "jarboleda-me"
    social:             #web social
      github:           jag10
      gitlab:           jag7
      twitter:          j_a_g_x
      linkedin:         167429134
    authors:
      Jeferson:
        name:           Jeferson Arboleda
        thumbnail:      'me2.min.png'
        images:
          - 'me2.png'
        bio:            'John Connor is the son of Sarah Connor and Kyle Reese, and the leader of the worldwide human resistance...'
        email:          me@jarboleda.me
        social:
          github:       jag10
          twitter:      j_a_g_x
          linkedin:     167429134
      # Sarah:            {}
    taxonomies:
      tag:                  "tags"
      pinned:               "pinned"
      serie:                "series"
      project:              "project"
# pygmentsuseclasses:   true # see https://github.com/richleland/pygments-css
