DefaultContentLanguage: "en"
googleAnalytics:        "UA-101857703-1"
menu:                   "main"
taxonomies:
  tag:                  "tags"
  pinned:               "pinned"
  serie:                "series"
  project:              "project"
paginate:               5
baseURL:                "https://www.jarboleda.me"
MetaDataFormat:         "YAML"
languages:
  en:
    weight :            0
    languageName :      "English"
    # baseURL:            "https://www.jarboleda.me"
    title:              "J. Arboleda"
    email:              "me@jarboleda.me"
    locale:             "en-US"
    description:        "The blog of Jefferson Arboleda, software engineer. It's focused on self improvement and overcoming challenges I find everyday"
    formspree:          "https://formspree.io/me@jarboleda.me"
    article_images :    "/content/articles/img/"
    menu:
      main:
      - Name:           "home"
        URL:            "/"
        weight:         1
      - Name:           "about me"
        URL:            "/extras/cv/"
        weight:         2
      - Name:           "projects"
        URL:            "/projects/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    disqusShortname :   "jarboleda-me"
    social:             #web social
      github:           jag10
      gitlab:           jag7
      # facebook:       nozzleio
      # facebook_admin: '17807199'
      twitter:          j_a_g_x
      # twitter_domain: nozzle.io
      # googleplus:     NozzleIo
      # pinterest:      nozzleio
      # instagram:      nozzleio
      # youtube:        nozzleio
      linkedin:         "jefferson-arboleda/"
    authors:
      Jeferson:
        name:           Jefferson Arboleda
        thumbnail:      'me.min.png'
        images:
          - 'me2.png'
        bio_title:      'Business Development Manager'
        # bio_summary:     "I recruit and manage consultants to develop [Alten's](https://alten.com/) Business in Madrid."
        bio_summary:    'I help [Alten](https://alten.com/) develop its IT business in Madrid.'
        email:          me@jarboleda.me
        social:
          github:       jag10
          gitlab:       jag7
          # facebook:   killskynet
          twitter:      j_a_g_x
          # googleplus: killskynet
          # pinterest:  killskynet
          # instagram:  killskynet
          # youtube:    killskynet
          linkedin:     167429134
      # Sarah:          {}
  es:
    weight :            1
    languageName :      "Spanish"
    # baseURL:            "https://www.jarboleda.me"
    title:              "J. Arboleda"
    email:              "me@jarboleda.me"
    locale:             "es-ES"
    description:        "El blog de Jefferson Arboleda, ingeniero informático. El blog está enfocado en la mejora de mis habilidades y en la superación de los retos que encuentro en mi día a día"
    formspree:          "https://formspree.io/me@jarboleda.me"
    article_images :    "/content/articles/img/"
    menu:
      main:
      - Name:           "home"
        URL:            "/es/"
        weight:         1
      - Name:           "sobre mi"
        URL:            "/extras/cv/"
        weight:         2
      - Name:           "proyectos"
        URL:            "/projects/"
        weight:         3
      - Name:           "github"
        URL:            "https://github.com/jag10"
        weight:         4
      - Name:           "gitlab"
        URL:            "https://gitlab.com/jag7"
        weight:         5
    disqusShortname :   "jarboleda-me"
    social:             #web social
      github:           jag10
      gitlab:           jag7
      twitter:          j_a_g_x
      linkedin:         "jefferson-arboleda/"
    authors:
      Jeferson:
        name:           Jefferson Arboleda
        thumbnail:      'me.min.png'
        images:
          - 'me2.png'
        bio_title:      'Business Development Manager'
        bio_summary:    "Recluto y gestiono consultores para desarrollar los negocios de [Alten](https://alten.com/) en Madrid."
        email:          me@jarboleda.me
        social:
          github:       jag10
          twitter:      j_a_g_x
          linkedin:     "jefferson-arboleda/"
      # Silvia:          {}
    taxonomies:
      tag:              "tags"
      pinned:           "pinned"
      serie:            "series"
      project:          "project"
# pygmentsuseclasses:   true # see https://github.com/richleland/pygments-css
